### ISSUE TITLE
Build process issues

### ISSUE THREAD

**Issue by ariutta** [bridgedb/bridgedbjs#3]
The build process from `gulp build` currently seems to not include the dist files, which means that you cannot run `gulp publish` immediately after building. Would be better to merge the gulp directory from this lib into [workflow-bob](https://github.com/ariutta/workflow-bob).

Also, it would be nice to avoid checking all the built files (dist, test, and demo) into master in order to limit the size of the repo when cloning it.

**Comment by ariutta** [comment]
Does npm automatically pull the latest tag published to github?

**Comment by ariutta** [comment]
```
Error: Command failed: /bin/sh -c npm publish
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.9
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 5.0.6." : bridgedb
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andersriutta/Sites/bridgedbjs/npm-debug.log

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

**Comment by ariutta** [comment]
@jacobwindsor I'm moving away from gulp to NPM scripts.

Some of the scripts I have in [package.json](https://github.com/bridgedb/bridgedbjs/blob/c9c62df8487f49f1ad7a1c2614b6680d879331e7/package.json) are outdated, like anything with `-old` in its name.

**Comment by ariutta** [comment]
@jacobwindsor I want users of this library to be able to pull in different parts independently. For example, if a user wants to use just the API client, they could do:

```js
import bridgedb from 'bridgedb';
var bridgedb = new Bridgedb();
```

or if the user just wanted the DataSourceSelect UI component:

```js
import { DataSourceSelect } from 'bridgedb/ui';
```
